//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarСatalogues
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarSet()
        {
            this.AutopartSet = new HashSet<AutopartSet>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public string CarBrand { get; set; }
        public string Year { get; set; }
        public int IdAutomaker { get; set; }
    
        public virtual Automaker Automaker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutopartSet> AutopartSet { get; set; }
    }
}
