//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarСatalogues
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shops
    {
        public int Id { get; set; }
        public string NameShop { get; set; }
        public string Address { get; set; }
        public int IdAutopart { get; set; }
    
        public virtual AutopartSet AutopartSet { get; set; }
    }
}
